### PR TITLE
Regenerate api code

### LINKED ISSUE #9: Invalid UTF-8 characters found in POST body
I have the following test:

``` haskell
module ThirdParty.StripeAPISpec (spec) where

import qualified Network.HTTP.Client as HTTPClient
import qualified StripeAPI           as Stripe

import Test.Hspec (Spec, describe, expectationFailure, it)

import TestUtils

spec :: Spec
spec = do
  describe "checkout sessions" $ do
    it "should contain a payment intent and a session url" $ do
      let params = (Stripe.mkPostCheckoutSessionsRequestBody "http://localhost:3000/" "http://localhost:3000/")
                   { Stripe.postCheckoutSessionsRequestBodyLineItems = Just [lineItems]
                   , Stripe.postCheckoutSessionsRequestBodyMode = Just Stripe.PostCheckoutSessionsRequestBodyMode'EnumPayment
                   , Stripe.postCheckoutSessionsRequestBodyClientReferenceId = Just "some-booking-id"
                   }
          lineItems = Stripe.mkPostCheckoutSessionsRequestBodyLineItems'
                      { Stripe.postCheckoutSessionsRequestBodyLineItems'PriceData = Just priceData
                      , Stripe.postCheckoutSessionsRequestBodyLineItems'Quantity = Just 3
                      }
          priceData = (Stripe.mkPostCheckoutSessionsRequestBodyLineItems'PriceData' "EUR")
                      { Stripe.postCheckoutSessionsRequestBodyLineItems'PriceData'ProductData = Just productData
                      , Stripe.postCheckoutSessionsRequestBodyLineItems'PriceData'UnitAmount = Just 100
                      }
          productData = Stripe.mkPostCheckoutSessionsRequestBodyLineItems'PriceData'ProductData' "foobar2000-î"
          getCheckout = Stripe.postCheckoutSessions params
          conf = Stripe.defaultConfiguration
                   { Stripe.configSecurityScheme = Stripe.bearerAuthenticationSecurityScheme testStripeAPIKey
                   }
      res <- Stripe.runWithConfiguration conf getCheckout
      case HTTPClient.responseBody res of
        Stripe.PostCheckoutSessionsResponse200 session -> do
          let mPaymentIntentId = Stripe.checkout'sessionPaymentIntent session
              mSessionUrl = Stripe.checkout'sessionUrl session
          case (mSessionUrl, mPaymentIntentId) of
            (Just _, Just (Stripe.Checkout'sessionPaymentIntent'Text _)) ->
              pure ()
            others -> expectationFailure $
              "Did not find sessionPaymentIntent and sessionUrl in " <> show others
        other -> expectationFailure $ "Did not find session response: " <> show other
```

Nothing special here, but note the `î` in the `ProductData` field. This tests fails with the following message:
```
  1) ThirdParty.StripeAPI, checkout sessions, should contain a payment intent and a session url
       Did not find session response: PostCheckoutSessionsResponseDefault (Error {errorError = ApiErrors {apiErrorsCharge = Nothing, apiErrorsCode = Just "invalid_utf8_in_post_body", apiErrorsDeclineCode = Nothing, apiErrorsDocUrl = Nothing, apiErrorsMessage = Just "Invalid UTF-8 characters found in POST body: \"foobar2000-\\xEE\".  For assistance, please contact support@stripe.com.", apiErrorsParam = Nothing, apiErrorsPaymentIntent = Nothing, apiErrorsPaymentMethod = Nothing, apiErrorsPaymentMethodType = Nothing, apiErrorsSetupIntent = Nothing, apiErrorsSource = Nothing, apiErrorsType = ApiErrorsType'EnumInvalidRequestError}})
```
Removing said `î` the test succeeds.

I haven't really looked into this yet, just discovered the issue. Do you have any suggestion what's wrong here? Can you give me pointers?

### PR DESCRIPTION
**Pull request by thomasbach-dev**
Original motivation is to fix #9 – so I updated the the code generator and regenerated the code. The diff is suprisingly large. I guess the code was not generated for a while.

I'm currently compiling locally to see if my tests still run as expected.

EDIT: Tests are running fine here.

### CODE REVIEW

**Comment by joel-bach** [comment]
Yes, the code in this repository has not been regenerated for quite a while. The reason for this is that the usability of the Stripe API with all the code is quite low due to the long compile times. I would generally advice to use the the code generator (https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator) directly even for the Stripe API and only generate the operations you actually need. This will reduce the compile time a lot and you can even white-list the schemas you use to decrease it further.

Nevertheless, I appreciate your effort in updating this repository as well!

**Comment by thomasbach-dev** [comment]
Sorry for the noise, I just noticed that `*.hs-boost` files are actually important, added them from the generated code and amended it.

**Comment by thomasbach-dev** [comment]
@joelfisch Thanks for merging. :)
Yeah, compile times are heavy for this one. Personally I don't care too much about this as long as it's a third-party library, so that I can use caches.
I was wondering -- the above sounds like you are not planing to do releases anymore. So do you think about deprecating this library and advise people to simply generate the code as you described above?
It would be sad. The OpenAPI codegen tool is quite nice and I think you need some kind of posterchild in order for people to be aware of it. Stripe is quite a good candidate for it, I guess.

**Comment by joel-bach** [comment]
TBH, I did not make any decision yet - but hearing that people actually use it helps to keep this library going :smile: But there is definitely more commitment on the generator than this repo, although I agree with you about the posterchild.
Currently, I am not actively updating the code in this repository but I am open to do it if someone needs an update. Do you use this repository directly or do you use the version on Hackage?

**Comment by thomasbach-dev** [comment]
I used to use the version from hackage. But yeah, I forked and am currently working with that fork. But I would not have found the whole project if it were not on hackage!
I used it to generate API bindings for Weclapp as well: https://github.com/thomasbach-dev/Weclapp-Haskell-Library, so the code generator already proved to be quite useful to me. But it took me a while to get comfortable wtih tooling, so I guess for the majority of the users it would be much simpler if there is something released on Hackage.

**Pull request merged**
